name: BCPC
favicon: null
layout_spectrum: 0.49549
typography_spectrum: 0.58578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#73abfe'
    - '#050601'
    - '#fefefe'
    - '#e5ad45'
    - '#747b4b'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
