name: BCPC
favicon: null
layout_spectrum: 0.49549
typography_spectrum: 0.58578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#649af4'
    - '#010300'
    - '#3a3424'
    - '#707553'
    - '#e2d7d9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
